config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }
  
  get "contact",to: "page#contact"
  get "about", to: "page#about"
  get "error", to: "page#error"
  root "page#home"


  resources :shops do
    resources :products do 
      post :addProductId
      post :confirm_cart
      collection do
        get :customer_view
      end
    end
    resources :orders
    collection do 
      get :customer_view
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shop.rb
class Shop < ApplicationRecord
    belongs_to :user
    has_many :products, dependent: :delete_all, validate: false
    has_many :orders, dependent: :destroy
    acts_as_paranoid

    mount_uploader :logo, UserImageUploader
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.where(user_id: current_user.id)
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.really_destroy!
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #shops_customers for show shop images to user
  def customer_view
    @shops=Shop.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :description, :catagory, :sweet_line, :logo).merge(:user_id => current_user.id)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_with(model: shop, local: true) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :catagory %>
    <%= form.text_area :catagory %>
  </div>

  <div class="field">
    <%= form.label :sweet_line %>
    <%= form.text_area :sweet_line %>
  </div>

  <div class="field">
    <%= form.label "Attachment" %>
    <%= form.file_field :logo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shops/customer_view.html.erb
<div class="container">
    <div class="container-fluid">
        <div class="row match-height">
            <% @shops.each do |shop| %>
                <div class="col-xl-4 col-md-6 col-sm-12 card-content">
                    <% if current_user && current_user.id==shop.user_id %>
                        <%= link_to image_tag(shop.logo.to_s,:align=>"middle", width: '350px',height: '350px'), shop_products_path(shop) %>
                    <% else %>
                        <%= link_to image_tag(shop.logo.to_s,:align=>"middle", width: '350px',height: '350px'), customer_view_shop_products_path(shop) %>
                    <% end %>
                    <div class="card-body">
                        <p classs="card-title"><%= shop.name %></p>
                        <p class="card-text"><%= shop.description %></p>
                    </div> 
                </div>
                
            <% end %>
        </div>
    </div>
</div>

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<div class="container">
  <h1>Shops</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Catagory</th>
        <th>Sweet line</th>
        <th>Logo</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @shops.each do |shop| %>
        <tr>
          <td><%= shop.name %></td>
          <td><%= shop.description %></td>
          <td><%= shop.catagory %></td>
          <td><%= shop.sweet_line %></td>
          <td><%= image_tag(shop.logo.to_s, width: '50px',:align=>"middle") %> </td>
          <td><%= link_to 'Show', shop %></td>
          <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
          <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= link_to 'Products', shop_products_path(shop) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Shop', new_shop_path %>
</div>

app/views/shops/new.html.erb
<div class="container">
    <h1>New Shop</h1>

    <%= render 'form', shop: @shop %>

    <%= link_to 'Back', shops_path %>
</div>

app/views/shops/show.html.erb
<div class="container">
  <p>
    <strong>Name:</strong>
    <%= @shop.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @shop.description %>
  </p>

  <p>
    <strong>Catagory:</strong>
    <%= @shop.catagory %>
  </p>

  <p>
    <strong>Sweet line:</strong>
    <%= @shop.sweet_line %>
  </p>

  <p>
    <%= image_tag(@shop.logo.to_s, width: '150px',:align=>"middle") %> 
  </p>

  <%= link_to 'Edit', edit_shop_path(@shop) %> |
  <%= link_to 'Back', shops_path %>
</div>