config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }
  
  get "contact",to: "page#contact"
  get "about", to: "page#about"
  get "error", to: "page#error"
  root "page#home"


  resources :shops do
    resources :products do 
      post :addProductId
      post :confirm_cart
      collection do
        get :customer_view
      end
    end
    resources :orders
    collection do 
      get :customer_view
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a href="#" class="navbar-brand">Shopify</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#content" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="content">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item nav-link">
        <%= link_to 'Home', root_path%>
      </li>
      <li class="nav-item nav-link">
        <%= link_to 'About', about_path %>
      </li>
      <li class="nav-item nav-link">
        <%= link_to 'Contact', contact_path %>
      </li>
      <% if current_user %>
        <li class="nav-item nav-link">
          <%= link_to 'Shops', shops_path %>
        </li>
      <% end %>
      <li class="nav-item nav-link">
        <%= link_to 'Shop Customer View', customer_view_shops_path %>
      </li>
    </ul>
    <ul class="navbar-nav">
      <% if current_user %>
        <li class="nav-item nav-link">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li class="nav-item nav-link">
          <%= link_to 'Register', new_user_registration_path %>
        </li>
        <li class="nav-item nav-link">
          <%= link_to 'Sign In', new_user_session_path %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>