config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }
  
  get "contact",to: "page#contact"
  get "about", to: "page#about"
  get "error", to: "page#error"
  root "page#home"


  resources :shops do
    resources :products do 
      post :addProductId
      post :confirm_cart
      collection do
        get :customer_view
      end
    end
    resources :orders
    collection do 
      get :customer_view
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    belongs_to :shop
    has_many :order_products, dependent: :destroy
    has_many :products, through: :order_products
    acts_as_paranoid

    after_initialize :set_defaults

    def set_defaults
        self.status ||= 'Request Sent' 
    end

    def self.order_product_table_update(user_id)
        @a=$redis.rpop(user_id);
        while @a != nil
            @a=$redis.rpop(user_id)
        end
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :set_shop

  # GET /orders
  # GET /orders.json
  def index
    @orders = @shop.orders
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @orders =Order.find(params[:id]).products.with_deleted
  end

  # GET /orders/new
  def new
    @order = @shop.orders.build
  end

  # GET /orders/1/edit
  def edit
    @order=@shop.orders.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = @shop.orders.create(:shop_id => params[:shop_id],:user_id => current_user.id)

    # Order.order_product_table_update(current_user.id)

    OrderProduct.order_product_table_update(current_user.id,@order.id)

    respond_to do |format|
      if @order.save
        format.html { redirect_to shop_orders_url(@order.shop_id), notice: 'Order was successfully created.'}
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    @oredr=@shop.orders.find(params[:id])
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to shop_orders_url(@order.shop_id), notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order=@shop.orders.find(params[:id])
    @order.really_destroy!
    respond_to do |format|
      format.html { redirect_to shop_orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:status).merge(:user_id => current_user.id)
    end

    def set_shop
      @shop = Shop.find(params[:shop_id])
    end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for([@order.shop,@order]) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', edit_shop_order_path(@order.shop_id,@order) %> |
<%= link_to 'Back', shop_products_path(@order.shop_id) %>

app/views/orders/index.html.erb
<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.status %></td>
        <td><%= link_to 'Show', shop_order_path(order.shop_id,order) %></td>
        <td><%= link_to 'Edit', edit_shop_order_path(order.shop_id,order) %></td>
        <td><%= link_to 'Destroy', shop_order_path(order.shop_id,order), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_shop_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', shop_orders_path %>

app/views/orders/show.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Purchasing price</th>
      <th>Image</th>
      <th>Catagory</th>
      <th>Shop</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.purchasing_price %></td>
        <td><%= image_tag(product.image.to_s, width:'50x', :align=>'middle') %></td>
        <td><%= product.catagory %></td>
        <td><%= product.Shop %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_shop_order_path(@order.shop_id,@order) %> |
<%= link_to 'Back', shop_orders_path %>