config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'user/sessions',
    registrations: 'user/registrations'
  }
  
  get "contact",to: "page#contact"
  get "about", to: "page#about"
  get "error", to: "page#error"
  root "page#home"


  resources :shops do
    resources :products do 
      post :addProductId
      post :confirm_cart
      collection do
        get :customer_view
      end
    end
    resources :orders
    collection do 
      get :customer_view
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord

    has_many :order_products

    acts_as_paranoid

    mount_uploader :image, UserImageUploader
    
    def self.addProduct(user_id,product_id)
        if ($redis.exists(user_id))
            $redis.rpush(user_id,product_id);
        else
            $redis.rpush(user_id, product_id)
        end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_shop

  # GET /products
  # GET /products.json
  def index
    @products = @shop.products
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @products = @shop.products.find(params[:id])
  end

  # GET /products/new
  def new
    @product = @shop.products.build
    respond_to do |format|
      format.html 
    end
  end

  # GET /products/1/edit
  def edit
    @product=@shop.products.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product=@shop.products.create(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to shop_products_url(@product.shop_id), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: shop_url(@product.shop_id) }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product=@shop.products.find(params[:id])
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to shop_products_url(@product.shop_id), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: shop_url(@product.shop_id) }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product=@shop.products.find(params[:id])
    @product.destroy
    respond_to do |format|
      format.html { redirect_to shop_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def addProductId
    Product.addProduct(current_user.id,params[:product_id])
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  def customer_view
    @products = @shop.products
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :purchasing_price, :image, :catagory, :belongs_to, :Shop)
    end

    def set_shop
      @shop=Shop.find(params[:shop_id])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for([@shop,@product]) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :purchasing_price %>
    <%= form.text_field :purchasing_price %>
  </div>

  <div class="field">
    <%= form.label "Attachment" %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :catagory %>
    <%= form.text_area :catagory %>
  </div>

  <div class="field">
    <%= form.hidden_field :Shop %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/customer_view.html.erb
<div class="row match-height">
    <% @products.each do |product| %>
        <div class="col-xl-3 col-md-2 col-sm-1">
            <div class="card" style="height: 451.109px;">
                <div class="card-content">
                    <%= link_to image_tag(product.image.to_s,class:"card-img-top img-fluid"), shop_product_addProductId_path(product.shop_id,product),remote: true, method: :post %>
                    <div class="card-body">
                        <p classs="card-title"><%= product.title %></p>
                        <p class="card-text"><%= product.description %></p>
                        <p class="card-text">Price: <%= product.price %></p>
                    </div> 
                </div>
            </div>
        </div>
    <% end %>
</div>
<%= link_to 'Confirm Order',shop_orders_path, method: :post%>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', edit_shop_product_path(@product.shop_id,@product.id) %> |
<%= link_to 'Back', shop_products_path(@product.shop_id) %>

app/views/products/index.html.erb
<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Purchasing price</th>
      <th>Image</th>
      <th>Catagory</th>
      <th>Shop</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.purchasing_price %></td>
        <td><%= image_tag(product.image.to_s, width:'50x', :align=>'middle') %></td>
        <td><%= product.catagory %></td>
        <td><%= product.Shop %></td>
        <td><%= link_to 'Show', shop_product_path(product.shop_id,product) %></td>
        <td><%= link_to 'Edit', edit_shop_product_path(product.shop_id,product) %></td>
        <td><%= link_to 'Destroy', shop_product_path(product.shop_id,product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Add to Cart', shop_product_addProductId_path(product.shop_id,product), remote: true, method: :post %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Order',shop_orders_path%>

<%= link_to 'Confirm Order',shop_orders_path, method: :post%>
<br>
<%= link_to 'back', shops_path %>
<%= link_to 'New Product', new_shop_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', shop_products_path %>

app/views/products/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Purchasing price:</strong>
  <%= @product.purchasing_price %>
</p>

<p>
  <%= image_tag(@product.image.to_s, width:'150x', :align=>'middle') %>
</p>

<p>
  <strong>Catagory:</strong>
  <%= @product.catagory %>
</p>

<p>
  <strong>Shop:</strong>
  <%= @product.Shop %>
</p>

<%= link_to 'Edit', edit_shop_product_path(@product) %> |
<%= link_to 'Back', shop_products_path %>